### ISSUE TITLE
REPL copy/paste friendly output formatter

### ISSUE THREAD

**Issue by meeuw** [dbcli/cli_helpers#12]
What I really like of Python is that you can easily copy-paste the output from a Python script (a printed dict or list) back in your Python script.

I'd like to do this also in dbcli for example when duplicating rows; I know in a perfect world the database should be normalized and rows shouldn't have duplicate data but I don't live in that perfect world 😄

I have the following use case, if you have the following table:
```
CREATE TABLE `dmtest` (
  `a` int(10) NOT NULL AUTO_INCREMENT,
  `b` int(10) DEFAULT NULL,
  `c` int(10) DEFAULT NULL,
  `d` int(10) DEFAULT NULL,
  PRIMARY KEY (`a`)
```
And you'd like to duplicate all rows with `b = 1` to `b = 2` I'd use the following command:
```
> select * from dmtest where b = 1
+---+---+---+---+
| a | b | c | d |
+---+---+---+---+
| 1 | 1 | 2 | 3 |
| 4 | 1 | 3 | 2 |
| 5 | 1 | 4 | 1 |
+---+---+---+---+
> insert into dmtest select null, 2, c, d from dmtest where b = 1
```
Now it would be *really* useful if I could have copied "a, b, c, d" (the result of dmtest.*) into the new query. Especially when you have a lot of columns to duplicate.

It would also be nice if you could easily copy-paste the data to an insert query like:
```
CREATE TEMPORARY TABLE tmpdmtest like dmtest;
INSERT INTO dmtest VALUES (1, 1, 2, 3),  (4, 1, 3, 2), (5, 1, 4, 1)
```
So I'm thinking of an output format like:
```
> select * from dmtest where b = 1
a,b,c,d
(1, 1, 2, 3), 
(4, 1, 3, 2),
(5, 1, 4, 1)
```

I'll try to make a PR for this, please let me know if you have more suggestions.

**Comment by tsroten** [comment]
@meeuw Closing this issue since you added this feature to mycli :smile:.
