### ISSUE TITLE
Move strip_ansi to main utils

### ISSUE THREAD

**Issue by jayvdb** [dbcli/cli_helpers#41]
It is useful to be able to strip the ansi emitted by other cli tools, in order to parse the output.

@coala needs something like that for https://github.com/coala/coala/issues/5281 , and we're looking for existing libraries which might do the trick for us.

**Comment by meeuw** [comment]
Hm that sounds like a good idea, we also have some stripping in:
https://github.com/dbcli/mycli/blob/master/test/features/steps/wrappers.py#L13
https://github.com/dbcli/pgcli/blob/master/tests/features/steps/wrappers.py#L12
https://github.com/dbcli/mssql-cli/blob/master/tests/features/steps/wrappers.py#L12

So it would be nice if we could generalize this in cli_helpers!
